# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('open_src_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensrcproject',
            name='project_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
