# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_src_projects', '0002_auto_20170201_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='project',
        ),
        migrations.AddField(
            model_name='opensrcproject',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
